### ISSUE TITLE
Plugin assumes XInputGetState will be called first

### ISSUE THREAD

**Issue by CookiePLMonster** [araghon007/X1nput#3] opened 2019-03-18 14:44 UTC
I can totally see games call XInputGetCapabilities before XInputGetState, and that will cause a crash.

Current `m_gamepad` initialization is also not thread safe, so in an unlikely event of two thread racing unexpected results may occur.

**Comment by araghon007** [comment] 2019-03-18 15:01
Well, the only issue I found with XInputGetCapabilities is games not accepting controller input.

I was able to debug an app that crashed using this DLL and I found out the crash is caused by a module not being loaded, so I'm assuming it's an issue with WinRT, which Windows.Gaming.Input is using. 

Also, I will look into thread safety.

**Comment by CookiePLMonster** [comment] 2019-03-18 15:03
That doesn't really matter. `m_gamepad` is being initialized only in GetState so any other function being called before that will crash. That includes GetStateEx, which some apps are using instead of GetState.

**Comment by araghon007** [comment] 2019-03-18 15:05
Oh, right. I'll figure out a better way ASAP. The reason I did it this way, because initializing the game pad on DLL injection caused crashes, and I didn't figure out to delay the initialization.
Any suggestions?

**Comment by CookiePLMonster** [comment] 2019-03-18 15:07
[InitOnceExecuteOnce](https://docs.microsoft.com/en-us/windows/desktop/api/synchapi/nf-synchapi-initonceexecuteonce) on top of each function using `m_gamepad` where you initialize this pointer. It also handles thread safety for you, so it solves two problems at once!

**Comment by araghon007** [comment] 2019-03-18 21:00
Alright, I've updated the configurable branch. I know I should have asked sooner, but if you know a proper way to implement InitOnceExecuteOnce, please let me know.

**Comment by CookiePLMonster** [comment] 2019-03-18 21:55
I wanted to take a look and potentially submit a PR back, but looks like the project cannot be opened. Did you commit your .vcxproj changes only partially or something?

**Comment by araghon007** [comment] 2019-03-18 22:08
Sorry about that, the vcxproj should be fixed now

**Comment by araghon007** [comment] 2019-03-18 22:12
Ah, I just used the example by Microsoft. So I can safely remove all stuff related to creating an event object in the callback function?

**Comment by CookiePLMonster** [comment] 2019-03-18 22:13
Sure thing - just initialize `m_gamepad` there and don't worry about other stuff.

**Comment by araghon007** [comment] 2019-03-18 22:25
Alright, thanks a lot for the help

**Closed by araghon007** 2019-03-18 22:25 UTC
